### PR TITLE
alpha blending fix in scatterplots

### LINKED ISSUE #2011: [BUG] leftside color code is not matching the layout
**Describe the bug**
The color on the leftside is NOT matching the layout plot.

**To Reproduce**
1. cellxgene launch https://cellxgene-example-data.czi.technology/pbmc3k.h5ad
2. Color code by "leiden"
3. Only select cluster '2'
4. The color on the left side is NOT matching the layout.

**Expected behavior**
The color code (legend) on the left side is matching the color in the layout

**Screenshots**
image

**Version (please complete the following information):**
 - hosted
 - Browser chrome
 - Version [e.g. 0.13.0]:
 - Name: cellxgene
Version: 0.16.6
Summary: Web application for exploration of large scale scRNA-seq datasets
Home-page: https://github.com/chanzuckerberg/cellxgene
Author: Chan Zuckerberg Initiative
Author-email: cellxgene@chanzuckerberg.com
License: MIT
Location: /home/zouyang/anaconda3/envs/cellxgeneTest/lib/python3.8/site-packages
Requires: click, flatbuffers, Flask-Compress, Flask, pandas, fastobo, anndata, Flask-Cors, requests, tiledb, boto3, flask-server-timing, numpy, packaging, gunicorn, sqlalchemy, flask-talisman, numba, fsspec, flatten-dict, scipy, h5py, PyYAML, s3fs, Flask-RESTful

**Additional context**

### PR DESCRIPTION
**Pull request by bkmartinjr**
Both WebGL rendering shaders (scatterplot, main graph) failed to explicitly set blending configuration, and would misbehave on some platforms/configurations. In addition the components using these shaders would incorrectly set the "isNaN" flag on points that should not have the flag.

 This PR has the following changes:
* Explicit blending config added to both shaders, so we are not dependent on defaults.
* Rename shader feature flag `isNaN` to `isBackground`, which more accurately describes the semantics.
* Remove duplicate definitions of all flags
* Graph and Scatterplot components have more specific test for when the isBackground (previously isNaN) flag is set

Fixes #2011

### CODE REVIEW

**Comment by signechambers1** [comment]
@bkmartinjr This looks partially fixed, there is a color for all cell labels but I'm still seeing a mismatch in the small square of color in the left sidebar and the main canvas (seems to happen once there are 9 categories).
Screen Shot 2021-02-02 at 1 41 29 PM

**Comment by bkmartinjr** [comment]
@signechambers1 - can you provide me with the test case (data file and instructions)?  This looks more related to #2007, which I did not fix in this PR.  But I want to confirm.

**Comment by signechambers1** [comment]
Sure, I'm using the Krasnow Lung SmartSeq2 dataset and I created 10 of my own arbitrary cell selections in a test category. Your merge request above says this PR fixes #2007 at the end, did you mean #2011?

**Comment by bkmartinjr** [comment]
@signechambers1 - yes, I incorrectly specified the fix issue number.  This PR fixes #2011, _not_ #2007.  Apologies!

**Review by seve — APPROVED** [review]
LGTM! Tests were fixed in #2035

**Review by signechambers1 — APPROVED** [review]

**Pull request merged**
