### PR TITLE
feat[sastisfaction]: adding non-blocking security linting to cellxgene

### PR DESCRIPTION
**Pull request by jacobrheath**
#### Description
This PR introduces a security tool that is being worked on by @edulop91, @jacobrheath, and the [prodsec team](https://wiki.czi.team/display/TECH/Product+Security).
The tool combines reviewdog and semgrep to make educational security comments about dangerous functions and potentially bad code patterns relating to security.
The main priority of the tool is not to be annoying or blocking, but to bring security learning closer to the development lifecycle. We will do our best to make this tool non-blocking.

#### Notes
- This is a non-blocking tool, and purely for educational purposes. We encourage you to read any comments that are produced and reach out to the prodsec team if you'd like to learn more information.
- If you see a mistake (a comment was created that seems to not be relevant to the code or something similar), let us know! We want to make this as high-signal and non-noisy as possible.
- The tool only runs semgrep rules on the diff from the PR.
- We only have a short number of rules that run right now, but we plan to bring in more over time.
- We have no Python rules at this time, but plan to create some in the future, so expect no comments until those rules are made.

Comments will look like this:
image

- Each comment will have a short description, as well as links to more educational material.
- The addition of new rules or changes to the tool do not require modifications to this codebase.
- If you have rule suggestions or patterns you'd like to prevent in your app please let us know!
- We collect some data around which rules are getting triggered and what action they prompt. This will help us tune our rules, avoid false positives, and hopefully make this a high-quality integration. 

#### FAQs
- *How does this compare with other static analysis tools?*
We opted to use `semgrep` for now (with room to grow into possible different tools) since it gives us the chance to write rules that are not necessarily framework/language specific. We can share rules with other projects at CZI and write rules for various languages with the same format.

- *Will this block my work?*
Our primary goal with this tool is to bring "Security Awareness" earlier into to the development lifecycle. Our hope is this project will help us highlight certain patterns we hope to avoid by tying in external documentation, example code snippets, etc directly into the development cycle. We've spent some time making sure tests run quickly, they are non-blocking, and we collect metrics to make sure we drive down false positives. Data we collect includes the rule that was triggered, the line that triggered it, the repo/SHA/branch, and any corresponding comments/responses in the GitHub PR review.

### CODE REVIEW

**Comment by maniarathi** [comment]
Quick question -- I hesitate about adding extraneous code right now that has no impact on us (i.e. you state that there are no Python rules, but our backend is entirely Python). Can we introduce this later once there are Python rules at which point I'd like to try it out before creating a Github Action to run on every PR?

**Comment by jacobrheath** [comment]
Totally understand where you are coming from. And if you want to wait, I think that is fine. This PR would mainly be helping us make the tool better in the background. It would essentially allows us to test and revise rules against the changes in the repo without making any comments on your repo yet. We are starting to write Python rules, but they are currently hidden behind a feature flag. The idea would be we'd collect metrics on rules' performance and revise to make sure the rule is high signal and educational. Once it was "ready for release", we'd release the feature flag. I'd also mention we have tried really hard to make sure this runs fast and will never block a build. 

The tool isn't really designed to be run locally, but the main engine we use is [semgrep](https://semgrep.dev/). It's a free CLI tool that you can download and try yourself if you like. Once we've committed a few of the Python rules (or semgrep has a number of published rules on their development website), give them a try on your repo! The main difference from using the CLI and this tool is that we'd only scanning the diffs and not the entire codebase on each PR. 

Anyway, up to you. We'd love to get more people onboard, but not a hard requirement if you are not up for it. Cheers!

**Comment by jacobrheath** [comment]
@maniarathi we've added some Python rules! Not many, but some we think will be high signal enough to start with. Currently, the rules look for command injection, CSRF, and SSRF vulnerabilities. If you are interested in running it locally, the repo is [here](https://github.com/chanzuckerberg/sastisfaction). If you have go installed already, you should be able to `make run src=path/to/code/dir` to test it out. Happy to help too if you run into issues.

**Comment by maniarathi** [comment]
Thanks for the update @jacobrheath! I'm just catching up from vacation -- I have to spend this upcoming week catching up on stuff but I will take a look at this next week and check it out! Apologies for the delay.

**Comment by jacobrheath** [comment]
All good, no rush at all. I hope you had a great vacation!

**Comment by maniarathi** [comment]
LGTM -- down to try this out!

**Review by maniarathi — APPROVED** [review]

**Comment by jacobrheath** [comment]
Woot! Thanks @maniarathi. Hit me up if you see any weirdness/rules you'd like to add/false positives, or w/e. Happy to chat!

**Pull request merged**
