### PR TITLE
Add "picture" to the /userinfo endpoint.

### PR DESCRIPTION
**Pull request by bmccandless**
This may be null or a URL

 #1900

### CODE REVIEW

**Review by Bento007 — APPROVED** [review]
LGTM

**Review by seve — CHANGES_REQUESTED** [review]
Could you add a picture to the test_oauth type for testing purposes?

**Comment by bmccandless** [comment]
> Could you add a picture to the test_oauth type for testing purposes?

Okay, do you also need a way to test the "null" case?

**Comment by seve** [comment]
> Okay, do you also need a way to test the "null" case?

If it's easy on your end sure! Otherwise, I could mock it in the e2e testing.

**Comment by bmccandless** [comment]
> > Okay, do you also need a way to test the "null" case?
> 
> If it's easy on your end sure! Otherwise, I could mock it in the e2e testing.

How about a way for you to specify the picture when you login.
   localhost:5005/api/v0.2/login?picture=mypicture.png

This will login the test user will a picture, else picture will be null.
(I already have this setup for username, userid, email, so it's easy)

**Review by seve — APPROVED** [review]
Thanks Brian

**Pull request merged**
