### PR TITLE
[WIP] QOL Docs

### PR DESCRIPTION
**Pull request by csweaver**
(Due to a series of unexpected events I didn't get to finish/merge this before my last day)

Added some documentation for:
1. NPM Scripts that I've written for development and running FE and E2E tests
2. Makefile scripts
3. Making point/bugfix releases. 

Also
1. Switched the release steps for releasing to github and pypi. Releasing to pypi allows you to test the full release and if there is a problem then you can go back a few steps and don't have to worry about deleting a github release.
2. Fixed typos on the makefile.

Still working on the e2e test doc.

### CODE REVIEW

**Comment by colinmegill** [comment]
:) Thank you Charlotte!

**Comment by bkmartinjr** [comment]
@csweaver these changes look great.  I'm plan to review and then merge. Please let me know if you have any concerns.

Also, thanks for your contributions.  Very much appreciated!

**Comment by bkmartinjr** [comment]
@csweaver I am grabbing your edits and creating a fresh PR.  I'll link to this one.  Thank you so much for the docs work!

**Comment by bkmartinjr** [comment]
These changes were incorporated as part of #977.   Thank you @csweaver!

**Pull request closed without merging**
