### PR TITLE
Trimming out secondary dependencies from requirements

### PR DESCRIPTION
**Pull request by csweaver**

### CODE REVIEW

**Comment by csweaver** [comment]
@bkmartinjr I'm wondering if this might work to get install working on your computer. If we let scanpy manage it's own dependencies through pip we might not run into the error where it's missing tkinter

**Comment by mckinsel** [comment]
I still get tkinter problems when I pip install scanpy on some platforms. It's actually a `matplotlib` problem. [This](https://github.com/HumanCellAtlas/table-testing/blob/master/tasks/merge/merge_anndata/Dockerfile#L7) is what I've been doing to get it to work, but it feels somewhat shameful. However you can't easily install tkinter in some environments.

**Comment by bkmartinjr** [comment]
@csweaver - I was able to get install to work without this.   It just required the python-tk install you mentioned in #140 

That said, if we can remove unneeded dependencies, it seems like a win.

**Comment by csweaver** [comment]
@bkmartinjr It is not exactly removing unnecessary dependencies. Most everything is still getting installed. I'm just letting the top level module handle their own dependencies.

Initially, when creating the requirements file I just did a pip freeze and copied that. With this PR, I've gone through and only included the dependencies that are actually imported (with the exception of anndata where I'm using an old version deliberately). That said, I do think this PR should land.

**Pull request merged**
