### PR TITLE
Update scanpy version

### PR DESCRIPTION
**Pull request by sidneymbell**
Update scanpy version to 1.3.7.

Latest is 1.4, but all the features we want to integrate were in by 1.3.7 (most specifically the `import scanpy` instead of `import scanpy.api`).

### CODE REVIEW

**Comment by bkmartinjr** [comment]
@sidneymbell - has this also been tested against scanpy 1.4?

**Comment by neuromusic** [comment]
does this fix #542?

**Comment by csweaver** [comment]
@neuromusic short answer: No. Longer answer - this allows us to fix #542 but see #689 for some of the concerns we need to work out before we actually fix it.

**Comment by sidneymbell** [comment]
@jk - No. Please see #689.

**Comment by neuromusic** [comment]
I thought that the "latest scanpy" (is that 1.37? 1.4?) no longer drops genes from `.X` when performing louvain, etc, effectively solving the core issue in #542, since all genes are now present in `.X` and therefore available for viz.

**Comment by sidneymbell** [comment]
@neuromusic - That's one source of genes being filtered out. But, they're also often filtered / removed during normalization. That's what makes it tricky: you may want to color by a gene, but you didn't normalize those expression values and thus can't visualize them on the same scale.

**Comment by neuromusic** [comment]
I think I see where I was mixed up.

The new `highly_variable_genes` preprocessing function will leave them, but other preprocessing functions like `filter_genes` (which is used by prepare if there's no recipe) will still drop them.

**Comment by csweaver** [comment]
Yeah, we never use the `highly_variable_genes` method.

**Comment by jk** [comment]
> @jk - No. Please see #689.

I'm most probably not the one you want to mention.

**Comment by jk** [comment]
> @jk - No. Please see #689.

@csweaver I'm most probably not the one you want to mention.

**Comment by bkmartinjr** [comment]
@neuromusic - see two accidental mentions of "at" jk  above.

**Comment by bkmartinjr** [comment]
@csweaver verbally confirmed that our CI pipeline tests this against the latest version of ScanPy.

**Pull request merged**
