### PR TITLE
refactor: drop non-session auth from frontend

### PR DESCRIPTION
**Pull request by seve**
## Changes
- Dropped all references to jwt based auth

### CODE REVIEW

**Review by MDunitz — APPROVED** [review]
lgtm 
Were you able to launch the desktop version and create annotations with this removed?
Also this looks good re auth in the front end but can you also update the backend auth code to remove the non session based auth classes and remove the factory pattern?

**Comment by seve** [comment]
> Also this looks good re auth in the front end but can you also update the backend auth code to remove the non session based auth classes and remove the factory pattern?

This ticket was only for the frontend, I can jump onto the backend ticket too otherwise I was going to work on getting the dataset drawer off of desktop.  I forgot to link the issue, sorry!

**Review by tihuan — APPROVED** [review]
LGTM! Should we use this as feature branch for its BE counterpart to merge into, before we merge both into `main`? This way once we remove auth from BE, we can test it E2E to make sure it works!

**Comment by seve** [comment]
>  Should we use this as feature branch for its BE counterpart to merge into, before we merge both into main? This way once we remove auth from BE, we can test it E2E to make sure it works!

@MDunitz What do you think?

**Comment by MDunitz** [comment]
> > Should we use this as feature branch for its BE counterpart to merge into, before we merge both into main? This way once we remove auth from BE, we can test it E2E to make sure it works!
> 
> @MDunitz What do you think?

Does it currently work E2E? I think it should be safe to merge as is. I can work on a pr to remove the BE code today

**Pull request merged**
